baseURL = 'https://xXJRUSHMANXx.github.io/'
languageCode = 'en-us'
title = 'Alexanders Portfolio'
theme = 'PaperMod'
[params]
  homeInfoParams = { Title = "Benvingut al meu Portfolio", Content = "" }
  disableHomeContent = false